### PR TITLE
Update to SPT 3.10.x

### PR DESCRIPTION
**Pull request by GH-Dowo**

### CODE REVIEW

**Comment by GH-Dowo** [comment]
I am very interested in this project, but I noticed that it has not been updated for a long time, so I tried to update it myself.
In the "BotsGroup_AddEnemy_Patch" section, I almost rewrote it from scratch because I was unable to update it without errors on the original code. I am not sure if my changes will affect the functionality, perhaps you should consider rewriting this part back to its original state.

**Comment by JollyFrogs** [comment]
Hi GH-Dowo, 

I'm denying your pull request because the DLLs in your pull request are not digitally signed by BattleState Games. I verified their hash against recent DLL files for version 3.10 and they don't match. If you can please submit your changes for version 0.15.5.1 33420 (used by all recent SPT 3.10 versions) and add the signed DLL files, I'll happily review and merge.

**Review by JollyFrogs — COMMENTED** [review]
DLLs not digitally signed, not matching SHA256 of game version 33420

**Comment by GH-Dowo** [comment]
Emm, in fact, the DLLs I use come from my own game directory. Anyway, I will check it.

**Comment by JollyFrogs** [comment]
Thanks for submitting PR - I've just merged it and released the latest version :)

**Pull request closed without merging**
